a = input('Digite algo:')
print('O tipo primitivo desse valor é', type(a))
print('Só tem espaços?', a.isspace())
print('É um número?', a.isnumeric())
print('É alfabético?', a.isalpha())
print('É alfanumérico?', a.isalnum())
print('São somente letras maiúsculas?', a.isupper())
print('São somente letras minúsculas?', a.islower())
print('Está capitalizado (contém letras maiúsculas e minúsculas)?', a.istitle())
